# TCL File Generated by Component Editor 17.1
# Sat May 12 20:01:07 EEST 2018
# DO NOT MODIFY


#
# ibex "ibex" v1.0
#  2018.05.12.20:01:07
# ibex
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module ibex
#
set_module_property DESCRIPTION "ibex"
set_module_property NAME ibex
#set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Processors and Peripherals/Embedded Processors"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ibex
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ibex_integration
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false

add_fileset_file fifo_v2.sv SYSTEM_VERILOG PATH rtl_extra/fifo_v2.sv
add_fileset_file avalon_dbg_regif.sv SYSTEM_VERILOG PATH rtl_extra/avalon_dbg_regif.sv
add_fileset_file debug_rom.sv SYSTEM_VERILOG PATH riscv-dbg/debug_rom/debug_rom.sv
add_fileset_file debug_rom_one_scratch.sv SYSTEM_VERILOG PATH riscv-dbg/debug_rom/debug_rom_one_scratch.sv
add_fileset_file dm_pkg.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_pkg.sv
add_fileset_file dm_csrs.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_csrs.sv
add_fileset_file dm_mem.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_mem.sv
add_fileset_file dm_sba.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_sba.sv
add_fileset_file dm_top.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_top.sv

add_fileset_file ibex_pkg.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_pkg.sv

add_fileset_file prim_ram_1p_pkg.sv SYSTEM_VERILOG PATH ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_pkg.sv
add_fileset_file prim_util_pkg.sv SYSTEM_VERILOG PATH ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_pkg.sv
add_fileset_file prim_secded_pkg.sv SYSTEM_VERILOG PATH ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
add_fileset_file prim_onehot_check.sv SYSTEM_VERILOG PATH ibex_prim/prim_onehot_check.sv
add_fileset_file prim_onehot_mux.sv SYSTEM_VERILOG PATH ibex_prim/prim_onehot_mux.sv
add_fileset_file prim_buf.sv SYSTEM_VERILOG PATH ibex_prim/prim_buf.sv
add_fileset_file prim_clock_gating.sv SYSTEM_VERILOG PATH ibex_prim/prim_clock_gating.sv
add_fileset_file prim_clock_mux2.sv SYSTEM_VERILOG PATH ibex_prim/prim_clock_mux2.sv
add_fileset_file prim_flop.sv SYSTEM_VERILOG PATH ibex_prim/prim_flop.sv
add_fileset_file prim_ram_1p.sv SYSTEM_VERILOG PATH ibex_prim/prim_ram_1p.sv
add_fileset_file prim_ram_1p_scr.sv SYSTEM_VERILOG PATH ibex_prim/prim_ram_1p_scr.sv

add_fileset_file ibex_alu.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_alu.sv
add_fileset_file ibex_branch_predict.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_branch_predict.sv
add_fileset_file ibex_compressed_decoder.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_compressed_decoder.sv
add_fileset_file ibex_controller.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_controller.sv
add_fileset_file ibex_counter.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_counter.sv
add_fileset_file ibex_cs_registers.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_cs_registers.sv
add_fileset_file ibex_csr.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_csr.sv
add_fileset_file ibex_decoder.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_decoder.sv
add_fileset_file ibex_dummy_instr.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_dummy_instr.sv
add_fileset_file ibex_ex_block.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_ex_block.sv
add_fileset_file ibex_fetch_fifo.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_fetch_fifo.sv
add_fileset_file ibex_icache.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_icache.sv
add_fileset_file ibex_id_stage.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_id_stage.sv
add_fileset_file ibex_if_stage.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_if_stage.sv
add_fileset_file ibex_load_store_unit.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_load_store_unit.sv
add_fileset_file ibex_lockstep.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_lockstep.sv
add_fileset_file ibex_multdiv_fast.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_multdiv_fast.sv
add_fileset_file ibex_multdiv_slow.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_multdiv_slow.sv
add_fileset_file ibex_pmp.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_pmp.sv
add_fileset_file ibex_prefetch_buffer.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_prefetch_buffer.sv
add_fileset_file ibex_register_file_ff.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_register_file_ff.sv
add_fileset_file ibex_wb_stage.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_wb_stage.sv
add_fileset_file ibex_core.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_core.sv
add_fileset_file ibex_top.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_top.sv


add_fileset_file ibex_integration.sv SYSTEM_VERILOG PATH ibex_integration.sv TOP_LEVEL_FILE


add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
set_fileset_property SIM_VERILOG TOP_LEVEL ibex_integration

add_fileset_file fifo_v2.sv SYSTEM_VERILOG PATH rtl_extra/fifo_v2.sv
add_fileset_file avalon_dbg_regif.sv SYSTEM_VERILOG PATH rtl_extra/avalon_dbg_regif.sv
add_fileset_file debug_rom.sv SYSTEM_VERILOG PATH riscv-dbg/debug_rom/debug_rom.sv
add_fileset_file debug_rom_one_scratch.sv SYSTEM_VERILOG PATH riscv-dbg/debug_rom/debug_rom_one_scratch.sv
add_fileset_file dm_pkg.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_pkg.sv
add_fileset_file dm_csrs.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_csrs.sv
add_fileset_file dm_mem.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_mem.sv
add_fileset_file dm_sba.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_sba.sv
add_fileset_file dm_top.sv SYSTEM_VERILOG PATH riscv-dbg/src/dm_top.sv

add_fileset_file ibex_pkg.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_pkg.sv

add_fileset_file prim_ram_1p_pkg.sv SYSTEM_VERILOG PATH ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_ram_1p_pkg.sv
add_fileset_file prim_util_pkg.sv SYSTEM_VERILOG PATH ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_util_pkg.sv
add_fileset_file prim_secded_pkg.sv SYSTEM_VERILOG PATH ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_secded_pkg.sv
add_fileset_file prim_onehot_check.sv SYSTEM_VERILOG PATH ibex_prim/prim_onehot_check.sv
add_fileset_file prim_onehot_mux.sv SYSTEM_VERILOG PATH ibex_prim/prim_onehot_mux.sv
add_fileset_file prim_buf.sv SYSTEM_VERILOG PATH ibex_prim/prim_buf.sv
add_fileset_file prim_clock_gating.sv SYSTEM_VERILOG PATH ibex_prim/prim_clock_gating.sv
add_fileset_file prim_clock_mux2.sv SYSTEM_VERILOG PATH ibex_prim/prim_clock_mux2.sv
add_fileset_file prim_flop.sv SYSTEM_VERILOG PATH ibex_prim/prim_flop.sv
add_fileset_file prim_ram_1p.sv SYSTEM_VERILOG PATH ibex_prim/prim_ram_1p.sv
add_fileset_file prim_ram_1p_scr.sv SYSTEM_VERILOG PATH ibex_prim/prim_ram_1p_scr.sv

add_fileset_file ibex_alu.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_alu.sv
add_fileset_file ibex_branch_predict.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_branch_predict.sv
add_fileset_file ibex_compressed_decoder.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_compressed_decoder.sv
add_fileset_file ibex_controller.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_controller.sv
add_fileset_file ibex_counter.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_counter.sv
add_fileset_file ibex_cs_registers.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_cs_registers.sv
add_fileset_file ibex_csr.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_csr.sv
add_fileset_file ibex_decoder.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_decoder.sv
add_fileset_file ibex_dummy_instr.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_dummy_instr.sv
add_fileset_file ibex_ex_block.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_ex_block.sv
add_fileset_file ibex_fetch_fifo.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_fetch_fifo.sv
add_fileset_file ibex_icache.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_icache.sv
add_fileset_file ibex_id_stage.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_id_stage.sv
add_fileset_file ibex_if_stage.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_if_stage.sv
add_fileset_file ibex_load_store_unit.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_load_store_unit.sv
add_fileset_file ibex_lockstep.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_lockstep.sv
add_fileset_file ibex_multdiv_fast.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_multdiv_fast.sv
add_fileset_file ibex_multdiv_slow.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_multdiv_slow.sv
add_fileset_file ibex_pmp.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_pmp.sv
add_fileset_file ibex_prefetch_buffer.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_prefetch_buffer.sv
add_fileset_file ibex_register_file_fpga.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_register_file_fpga.sv
add_fileset_file ibex_wb_stage.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_wb_stage.sv
add_fileset_file ibex_core.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_core.sv
add_fileset_file ibex_top.sv SYSTEM_VERILOG PATH ibex/rtl/ibex_top.sv


add_fileset_file ibex_integration.sv SYSTEM_VERILOG PATH ibex_integration.sv TOP_LEVEL_FILE


#
# parameters
#
add_parameter IBEX_RV32E boolean true "IBEX_RV32E"
set_parameter_property IBEX_RV32E HDL_PARAMETER true
add_parameter IBEX_ICACHE boolean true "IBEX_ICACHE"
set_parameter_property IBEX_ICACHE HDL_PARAMETER true


#
# display items
#


#
# connection point clk_sink
#
add_interface clk_sink clock end
set_interface_property clk_sink ENABLED true
set_interface_property clk_sink EXPORT_OF ""
set_interface_property clk_sink PORT_NAME_MAP ""
set_interface_property clk_sink CMSIS_SVD_VARIABLES ""
set_interface_property clk_sink SVD_ADDRESS_GROUP ""

add_interface_port clk_sink clk_i clk Input 1


#
# connection point reset_sink
#
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clk_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_ni reset_n Input 1


#
# connection point po_reset_sink
#
add_interface po_reset_sink reset end
set_interface_property po_reset_sink associatedClock clk_sink
set_interface_property po_reset_sink synchronousEdges DEASSERT
set_interface_property po_reset_sink ENABLED true
set_interface_property po_reset_sink EXPORT_OF ""
set_interface_property po_reset_sink PORT_NAME_MAP ""
set_interface_property po_reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property po_reset_sink SVD_ADDRESS_GROUP ""

add_interface_port po_reset_sink po_rst_ni reset_n Input 1


#
# connection point ndm
#
add_interface ndm conduit end
set_interface_property ndm associatedClock clk_sink
set_interface_property ndm associatedReset ""
set_interface_property ndm ENABLED true
set_interface_property ndm EXPORT_OF ""
set_interface_property ndm PORT_NAME_MAP ""
set_interface_property ndm CMSIS_SVD_VARIABLES ""
set_interface_property ndm SVD_ADDRESS_GROUP ""

add_interface_port ndm ndmreset_o ndmreset_o Output 1
add_interface_port ndm ndmreset_ack_i ndmreset_ack_i Input 1


#
# connection point config
#
add_interface config conduit end
set_interface_property config associatedClock clk_sink
set_interface_property config associatedReset ""
set_interface_property config ENABLED true
set_interface_property config EXPORT_OF ""
set_interface_property config PORT_NAME_MAP ""
set_interface_property config CMSIS_SVD_VARIABLES ""
set_interface_property config SVD_ADDRESS_GROUP ""

add_interface_port config boot_addr_i boot_addr_i Input 32
add_interface_port config core_sleep_o core_sleep_o Output 1


#
# connection point interrupt_receiver
#
add_interface interrupt_receiver interrupt start
set_interface_property interrupt_receiver associatedAddressablePoint ""
set_interface_property interrupt_receiver associatedClock clk_sink
set_interface_property interrupt_receiver associatedReset reset_sink
set_interface_property interrupt_receiver irqScheme INDIVIDUAL_REQUESTS
set_interface_property interrupt_receiver ENABLED true
set_interface_property interrupt_receiver EXPORT_OF ""
set_interface_property interrupt_receiver PORT_NAME_MAP ""
set_interface_property interrupt_receiver CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_receiver SVD_ADDRESS_GROUP ""

add_interface_port interrupt_receiver irq_fast_i irq Input 15


#
# connection point avalon_master_instr
#
add_interface avalon_master_bus_instr avalon start
set_interface_property avalon_master_bus_instr addressUnits SYMBOLS
set_interface_property avalon_master_bus_instr associatedClock clk_sink
set_interface_property avalon_master_bus_instr associatedReset reset_sink
set_interface_property avalon_master_bus_instr bitsPerSymbol 8
set_interface_property avalon_master_bus_instr burstOnBurstBoundariesOnly false
set_interface_property avalon_master_bus_instr burstcountUnits WORDS
set_interface_property avalon_master_bus_instr doStreamReads false
set_interface_property avalon_master_bus_instr doStreamWrites false
set_interface_property avalon_master_bus_instr holdTime 0
set_interface_property avalon_master_bus_instr linewrapBursts false
set_interface_property avalon_master_bus_instr maximumPendingReadTransactions 0
set_interface_property avalon_master_bus_instr maximumPendingWriteTransactions 0
set_interface_property avalon_master_bus_instr readLatency 0
set_interface_property avalon_master_bus_instr readWaitTime 1
set_interface_property avalon_master_bus_instr setupTime 0
set_interface_property avalon_master_bus_instr timingUnits Cycles
set_interface_property avalon_master_bus_instr writeWaitTime 0
set_interface_property avalon_master_bus_instr ENABLED true
set_interface_property avalon_master_bus_instr EXPORT_OF ""
set_interface_property avalon_master_bus_instr PORT_NAME_MAP ""
set_interface_property avalon_master_bus_instr CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_bus_instr SVD_ADDRESS_GROUP ""
add_interface_port avalon_master_bus_instr bus_instr_addr address Output 32
add_interface_port avalon_master_bus_instr bus_instr_rdata readdata Input 32
add_interface_port avalon_master_bus_instr bus_instr_read read Output 1
add_interface_port avalon_master_bus_instr bus_instr_rvalid readdatavalid Input 1
add_interface_port avalon_master_bus_instr bus_instr_busy waitrequest Input 1


#
# connection point avalon_master_data
#
add_interface avalon_master_bus_data avalon start
set_interface_property avalon_master_bus_data addressUnits SYMBOLS
set_interface_property avalon_master_bus_data associatedClock clk_sink
set_interface_property avalon_master_bus_data associatedReset reset_sink
set_interface_property avalon_master_bus_data bitsPerSymbol 8
set_interface_property avalon_master_bus_data burstOnBurstBoundariesOnly false
set_interface_property avalon_master_bus_data burstcountUnits WORDS
set_interface_property avalon_master_bus_data doStreamReads false
set_interface_property avalon_master_bus_data doStreamWrites false
set_interface_property avalon_master_bus_data holdTime 0
set_interface_property avalon_master_bus_data linewrapBursts false
set_interface_property avalon_master_bus_data maximumPendingReadTransactions 0
set_interface_property avalon_master_bus_data maximumPendingWriteTransactions 0
set_interface_property avalon_master_bus_data readLatency 0
set_interface_property avalon_master_bus_data readWaitTime 1
set_interface_property avalon_master_bus_data setupTime 0
set_interface_property avalon_master_bus_data timingUnits Cycles
set_interface_property avalon_master_bus_data writeWaitTime 0
set_interface_property avalon_master_bus_data ENABLED true
set_interface_property avalon_master_bus_data EXPORT_OF ""
set_interface_property avalon_master_bus_data PORT_NAME_MAP ""
set_interface_property avalon_master_bus_data CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_bus_data SVD_ADDRESS_GROUP ""
add_interface_port avalon_master_bus_data bus_data_addr address Output 32
add_interface_port avalon_master_bus_data bus_data_rdata readdata Input 32
add_interface_port avalon_master_bus_data bus_data_read read Output 1
add_interface_port avalon_master_bus_data bus_data_rvalid readdatavalid Input 1
add_interface_port avalon_master_bus_data bus_data_busy waitrequest Input 1
add_interface_port avalon_master_bus_data bus_data_write write Output 1
add_interface_port avalon_master_bus_data bus_data_be byteenable Output 4
add_interface_port avalon_master_bus_data bus_data_wdata writedata Output 32
add_interface_port avalon_master_bus_data bus_data_resp response Input 2
add_interface_port avalon_master_bus_data bus_data_wrespvalid writeresponsevalid Input 1


#
# connection point avalon_slave_dm
#
add_interface avalon_slave_dm avalon end
set_interface_property avalon_slave_dm addressUnits SYMBOLS
set_interface_property avalon_slave_dm associatedClock clk_sink
set_interface_property avalon_slave_dm associatedReset reset_sink
set_interface_property avalon_slave_dm bitsPerSymbol 8
set_interface_property avalon_slave_dm burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_dm burstcountUnits WORDS
set_interface_property avalon_slave_dm explicitAddressSpan 0
set_interface_property avalon_slave_dm holdTime 0
set_interface_property avalon_slave_dm linewrapBursts false
set_interface_property avalon_slave_dm maximumPendingReadTransactions 0
set_interface_property avalon_slave_dm readLatency 0
set_interface_property avalon_slave_dm readWaitTime 1
set_interface_property avalon_slave_dm setupTime 0
set_interface_property avalon_slave_dm timingUnits Cycles
set_interface_property avalon_slave_dm writeWaitTime 0
set_interface_property avalon_slave_dm ENABLED true
set_interface_property avalon_slave_dm EXPORT_OF ""
set_interface_property avalon_slave_dm PORT_NAME_MAP ""
set_interface_property avalon_slave_dm CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_dm SVD_ADDRESS_GROUP ""
add_interface_port avalon_slave_dm dm_avalon_s_address address Input 12
add_interface_port avalon_slave_dm dm_avalon_s_readdata readdata Output 32
add_interface_port avalon_slave_dm dm_avalon_s_read read Input 1
add_interface_port avalon_slave_dm dm_avalon_s_write write Input 1
add_interface_port avalon_slave_dm dm_avalon_s_writedata writedata Input 32
add_interface_port avalon_slave_dm dm_avalon_s_byteenable byteenable Input 4


#
# connection point avalon_slave_dbgreg
#
add_interface avalon_slave_dbgreg avalon end
set_interface_property avalon_slave_dbgreg addressUnits SYMBOLS
set_interface_property avalon_slave_dbgreg associatedClock clk_sink
set_interface_property avalon_slave_dbgreg associatedReset reset_sink
set_interface_property avalon_slave_dbgreg bitsPerSymbol 8
set_interface_property avalon_slave_dbgreg burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_dbgreg burstcountUnits WORDS
set_interface_property avalon_slave_dbgreg explicitAddressSpan 0
set_interface_property avalon_slave_dbgreg holdTime 0
set_interface_property avalon_slave_dbgreg linewrapBursts false
set_interface_property avalon_slave_dbgreg maximumPendingReadTransactions 1
set_interface_property avalon_slave_dbgreg maximumPendingWriteTransactions 1
set_interface_property avalon_slave_dbgreg readWaitTime 1
set_interface_property avalon_slave_dbgreg setupTime 0
set_interface_property avalon_slave_dbgreg timingUnits Cycles
set_interface_property avalon_slave_dbgreg writeWaitTime 0
set_interface_property avalon_slave_dbgreg ENABLED true
set_interface_property avalon_slave_dbgreg EXPORT_OF ""
set_interface_property avalon_slave_dbgreg PORT_NAME_MAP ""
set_interface_property avalon_slave_dbgreg CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_dbgreg SVD_ADDRESS_GROUP ""
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_address address Input 10
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_readdata readdata Output 32
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_readdatavalid readdatavalid Output 1
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_read read Input 1
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_response response Output 2
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_write write Input 1
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_writedata writedata Input 32
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_writeresponsevalid writeresponsevalid Output 1
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_byteenable byteenable Input 4
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_chipselect chipselect Input 1
add_interface_port avalon_slave_dbgreg dbgreg_avalon_s_waitrequest_n waitrequest_n Output 1